name: Post derivative warning

on:
  pull_request:
    paths:
      - "*.csv"
      - "!plane-alert-db.csv"
      - "!plane-alert-pia.csv"
      - "!plane-alert-twitter-blocked.csv"
      - "!plane-alert-ukraine.csv"

jobs:
  postDerivativeWarning:
    runs-on: ubuntu-latest
    name: Post a warning pull request comment when a user changes a derivative file
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Display context
        run: echo '${{ toJSON(github) }}'

      - name: Retrieve warning message from READ_BEFORE_MAKING_CHANGES.md
        run: |
          echo "WARNING_MSG<<EOF" >> $GITHUB_ENV
          echo "$(cat READ_BEFORE_MAKING_CHANGES.md | tail -n +3)" >> $GITHUB_ENV 
          echo "EOF" >> $GITHUB_ENV

      - name: Post derivative warning
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ env.WARNING_MSG }}
          comment_tag: execution
